services:
  server:
    build: ./server  # Path to the directory containing your Go application
    container_name: go-server
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    environment:
      # Add any environment variables needed by your Go server
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_SSL: ${DB_SSL}
    depends_on:
      - db  # The server service depends on the database

  db:
    image: postgres:latest
    container_name: promo-rankings
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

volumes:
  pgdata:
  database:
